#!/usr/bin/env bash
# A script that transfers a file from our client to a server

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1

else

    file_path=$1
    ip=$2
    username=$3
    sshkey_path=$4

    scp -o "StrictHostKeyChecking=no" -i "$sshkey_path" "$file_path" "$username@$ip:~/"

fi