#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect below requirements
# Requirements:
# - Install nginx
# - Nginx should be listening on port 80
# - When querying Nginx at its root / with a GET request (requesting a page)
# using curl, it must return a page that contains the string Hello World!
# - /redirect_me is redirecting to another page.

REDIRECT301="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"
NOTFOUND404="error_page 404 /custom_404.html;\n\\tlocation = /custom_404.html {\n\t\t root /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
PATTERN="#error_page 404 /404.html;"

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee  /var/www/html/indix.html
sudo sed -i "30i $REDIRECT301" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "s@$PATTERN@$NOTFOUND404@" /etc/nginx/sites-available/default #uncomment and replace

sudo service nginx start
sudo service nginx reload