#!/usr/bin/env bash
# Bash script to configure Nginx on Ubuntu

REDIRECT301="location /redirect_me {\n\treturn 301 https://google.com;\n}\n"
NOTFOUND404="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\n\troot /usr/share/nginx/html;\n\tinternal;\n}"

# Update and install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Create a custom index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Add redirect and custom 404 error page only if not already present
if ! grep -q "location /redirect_me" /etc/nginx/sites-available/default; then
    sudo sed -i "/server_name _;/a \\    $REDIRECT301" /etc/nginx/sites-available/default
fi

if ! grep -q "error_page 404" /etc/nginx/sites-available/default; then
    sudo sed -i "/server_name _;/a \\    $NOTFOUND404" /etc/nginx/sites-available/default
fi

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Test and reload Nginx
if sudo nginx -t; then
    sudo systemctl restart nginx
else
    echo "Nginx configuration test failed."
    exit 1
fi
