#!/usr/bin/env bash
# Script to install and configure HAProxy for load balancing

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy configuration file
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log 127.0.0.1 local0
    log 127.0.0.1 local1 notice
    maxconn 2000
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    maxconn 2000
    timeout connect 5s
    timeout client  30s
    timeout server  30s

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 806533-web-01 100.26.246.61:80 check
    server 806533-web-02 54.237.93.3:80 check
EOF

# Enable HAProxy to be started by init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy to apply changes
sudo service haproxy restart
