#!/usr/bin/env bash
# A bash script that creates a MySQL dump of all databases
#+ and compresses it into a tar.gz archive.

# Exit if no password provided
if [ $# -ne 1 ]
then
    echo "Usage: $0 password"
    exit 1
fi

# Create MySQL dump with provided password
mysqldump -uroot -p"$1" --all-databases > backup.sql

# Get current date
DATE=$(date +%d-%m-%Y)

# Create tar archive and compress it with gzip
tar cf - backup.sql | gzip > "$DATE.tar.gz"
