#!/usr/bin/env bash
# Infinite loop creates file with pid, catches signal, and removes file/exits:
# Ctrl-C (SIGINT), kill (SIGTERM), and Ctrl-\ (SIGQUIT)

rmfile_n_exit() {
    rm -f /var/run/holbertonscript.pid
    exit
}

# Trap signals with specific messages and clean-up actions
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; rmfile_n_exit" SIGTERM
trap "echo 'I hate the kill command'; rmfile_n_exit" SIGQUIT

# Save the current process ID in a file
echo $$ > /var/run/holbertonscript.pid

# Infinite loop to print a message every 2 seconds
while true; do
    echo 'To infinity and beyond'
    sleep 2
done
