#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes:
#+ display hours from 0 to 12
#+ display minutes from 1 to 59

i=1
Hour=1
while [ "$i" -le 720 ]; do
	(( z="$i" % 60 ))
    if   (( "$z" != 0 ));
    	then
			echo "$i"
	else
		echo "Hour: $Hour"
		((Hour++))
	fi
	((i++))
	done