#!/usr/bin/env bash
# This script gives you information about the school file.
# file exists or not
# file is empty or not 
# file is a regular file or nothing

if [[ -e "./school" ]]; then
    echo "school file exists"
    if [[ -s "./school" ]]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
else 
    echo "school file does not exist"
fi 



if [[ -f "./school" ]]; then
    echo "school is a regular file"
fi
